#!/usr/bin/env sh
. "$(dirname "$0")/h"

echo 'Pre push baslasin yoxlasin gorek ne var ne yox'

npm install || { echo "❌ npm install uğursuz oldu"; exit 1; }

echo  'qaqa biz paketleri yukledik'

echo   'indi build edecik'

npm run build ||  {echo "kodun problem yeke kisisen get duzelt sonra push edersen"; exit 1 ;}

echo 'final'